# Generated by Django 2.2 on 2019-04-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', related_query_name='parentComment', to='forum.Comment'),
        ),
    ]
