# Generated by Django 2.2 on 2019-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('TCHR', 'Teacher'), ('STD', 'Student'), ('ADM', 'Admin')], default='STD', max_length=20),
        ),
    ]
