# Generated by Django 2.2 on 2019-04-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'permissions': (('can_add_class', 'Add Classes'), ('can_edit_class', 'Edit Classes')),
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
            options={
                'ordering': ['cl', 'date'],
                'permissions': [('can_make_announcement', 'Create Announcement'), ('can_edit_announcement', 'Edit Announcement'), ('can_delete_announcement', 'Delete Announcement')],
            },
        ),
    ]
